### ISSUE TITLE
No reponse to 17 - GetFunc when Airplay / Wi-Fi for HW-Q900a 1009.2

### ISSUE THREAD

**Issue by salvq** [bacl/WAM_API_DOC#6]
I have soundbar Samsung HW-Q900a and having an issue to get a input response when Airplay / Wi-Fi.

![image](https://user-images.githubusercontent.com/43242348/149638578-6cabe5bc-b8e6-450e-88e8-b70bcddf8d48.png)
When I switch to Spotify i.e. AirPlay Wi-Fi and excute the command, there is no reponse at all
```
$ curl 'http://192.168.1.112:56001/UIC?cmd=%3Cname%3EGetFunc%3C/name%3E'
^C
$
```

For instance HDMI1 or HDMI2 input, there is an instant response to command:
```
$ curl 'http://192.168.1.112:56001/UIC?cmd=%3Cname%3EGetFunc%3C/name%3E'
<?xml version="1.0" encoding="UTF-8"?><UIC><method>CurrentFunc</method><version>1.0</version><speakerip>192.168.1.112</speakerip><user_identifier></user_identifier><response result="ok"><function>hdmi1</function><submode></submode><connection>on</connection></response></UIC>pi@ebusd:~/zigbee2mqtt $
$
```

Firmware verions is HW-Q900AWWB-1009.2:
```
$ curl 'http://192.168.1.112:56001/UIC?cmd=%3Cname%3EGetSoftwareVersion%3C/name%3E'
<?xml version="1.0" encoding="UTF-8"?><UIC><method>SoftwareVersion</method><version>1.0</version><speakerip>192.168.1.112</speakerip><user_identifier></user_identifier><response result="ok"><version>HW-Q900AWWB-1009.2</version><displayversion>HW-Q900AWWB-1009.2</displayversion></response></UIC>
$
```

1.) Is there any other command to identify Airplay / Wi-Fi as input ?
2.) Is this related to soundbar version or firmware ?

Thanks

**Comment by bacl** [comment]
It's been a long time since I tinker with theses commands and with the speakers. Back then I probably would have an explanation but now I can't remember why. Also right now I can't test this, but from my notes: 

Try using `GetPlayStatus`  either as UIC or CPM (don't remember which one is it)
When playing Spotify it should return something like:
```
function: wifi
submode: cp
```

and to get what is currently playing use `GetRadioInfo` as CPM

If  `GetPlayStatus`  also fails, a possible work around is to infere the status using `GetMusicInfo` as UCI.  
When playing Spotify it should return something like errCode: `Wifi Sub Mode is CP`

**Comment by salvq** [comment]
Thank you @bacl , `GetPlayStatus` as CPM worked

```
curl 'http://192.168.1.112:56001/CPM?cmd=%3Cname%3EGetPlayStatus%3C/name%3E'
<?xml version="1.0" encoding="UTF-8"?><CPM><method>PlayStatus</method><version>0.1</version><speakerip>192.168.1.112</speakerip><user_identifier>public</user_identifier><response result="ok">
    <function>wifi</function>
    <submode>cp</submode>
    <cpname>Unknown</cpname>
    <playstatus>stop</playstatus>
</response>
</CPM>
```
